name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-version: 8.7
          arguments: build
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
      - name: Quality coverage
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          coverageCommand: make report
          files: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
